name: Python package


on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'

jobs:
  build:
    #to run on multiple python versions
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip3
           pip3 install -r requirements.txt
    - name: Convert ipynb to py for storage and diffing
      run: jupytext --set-formats ipynb,py:validation_dev_work/validation_data.ipynb
           jupytext --to ipynb validation_dev_work/jupytxt_validation_data.py
    # - name: Lint with Ruff
    #   run: |
    #     pip3 install ruff
    #     ruff --output-format=github .
    #   continue-on-error: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: pytest test/test_collection_integration.py 
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}
