name: Converts ipynb to py for diffing

on: [push]

jobs:
  build:
    #to run on multiple python versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install jupytext
    - name: Convert ipynb to py for storage and diffing
      run:
        jupytext --set-formats ipynb,py:percent validation_dev_work/validation_data.ipynb
