name: onver py to ipynb

on: [create]

jobs:
  build:
    #to run on multiple python versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install jupytext
    - name: Convert py to ipynb for dev work
      run:
        jupytext --to ipynb legacy_code/code_prototype.py
