name: Pytest Core Functionality


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip
           pip install -r requirements.txt
           pip install pytest
    - name: Test with pytest
      run: pytest test/test_collection_integration.py
